project_id = "sjsxjiozxwjepmshasgl"

[functions.start-interview]
verify_jwt = false

[functions.get-interview-results]
verify_jwt = false

[functions.analyze-interview]
verify_jwt = false

[functions.generate-report-pdf]
verify_jwt = false
